"""Initial migration

Revision ID: 20d0f383e99d
Revises: 
Create Date: 2025-12-24 13:51:42.692361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '20d0f383e99d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_changelogs_id'), table_name='changelogs')
    op.drop_table('changelogs')
    op.add_column('categories', sa.Column('banner_url', sa.String(length=255), nullable=True))
    op.add_column('categories', sa.Column('quote', sa.String(length=255), nullable=True))
    op.add_column('categories', sa.Column('quote_author', sa.String(length=50), nullable=True))
    op.alter_column('comments', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='评论内容',
               existing_nullable=False)
    op.alter_column('comments', 'content_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='内容类型',
               existing_nullable=False,
               existing_server_default=sa.text("'article'"))
    op.alter_column('comments', 'content_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='内容ID',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('comments', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               comment='评论者ID')
    op.alter_column('comments', 'parent_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='父评论ID',
               existing_nullable=True)
    op.alter_column('comments', 'reply_to_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='回复目标用户ID',
               existing_nullable=True)
    op.alter_column('comments', 'is_approved',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否审核通过',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('comments', 'like_count',
               existing_type=mysql.INTEGER(display_width=11),
               comment='点赞数',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('comments', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('comments', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_comments_content_type_id'), table_name='comments')
    op.drop_constraint(op.f('comments_ibfk_2'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('comments_ibfk_3'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'users', ['reply_to_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'comments', 'comments', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'nickname')
    op.drop_column('comments', 'email')
    op.drop_column('comments', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('avatar', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True))
    op.add_column('comments', sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.add_column('comments', sa.Column('nickname', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_ibfk_3'), 'comments', 'comments', ['parent_id'], ['id'])
    op.create_foreign_key(op.f('comments_ibfk_2'), 'comments', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_comments_content_type_id'), 'comments', ['content_type', 'content_id'], unique=False)
    op.alter_column('comments', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('comments', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('comments', 'like_count',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='点赞数',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('comments', 'is_approved',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否审核通过',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('comments', 'reply_to_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='回复目标用户ID',
               existing_nullable=True)
    op.alter_column('comments', 'parent_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='父评论ID',
               existing_nullable=True)
    op.alter_column('comments', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               comment=None,
               existing_comment='评论者ID')
    op.alter_column('comments', 'content_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='内容ID',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('comments', 'content_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='内容类型',
               existing_nullable=False,
               existing_server_default=sa.text("'article'"))
    op.alter_column('comments', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='评论内容',
               existing_nullable=False)
    op.drop_column('categories', 'quote_author')
    op.drop_column('categories', 'quote')
    op.drop_column('categories', 'banner_url')
    op.create_table('changelogs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('version', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_changelogs_id'), 'changelogs', ['id'], unique=False)
    # ### end Alembic commands ###
