"""add_category_fields_and_fix_models

Revision ID: 27ecd5cfca7c
Revises: 20d0f383e99d
Create Date: 2026-01-05 10:50:50.781968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '27ecd5cfca7c'
down_revision: Union[str, Sequence[str], None] = '20d0f383e99d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 获取数据库连接和检查器
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # 检查 categories 表的列
    cat_columns = [c['name'] for c in inspector.get_columns('categories')]
    if 'banner_url' not in cat_columns:
        op.add_column('categories', sa.Column('banner_url', sa.String(length=255), nullable=True))
    if 'quote' not in cat_columns:
        op.add_column('categories', sa.Column('quote', sa.String(length=255), nullable=True))
    if 'quote_author' not in cat_columns:
        op.add_column('categories', sa.Column('quote_author', sa.String(length=50), nullable=True))
    
    # 检查 comments 表的列和索引
    comment_columns = [c['name'] for c in inspector.get_columns('comments')]
    comment_indexes = {idx['name'] for idx in inspector.get_indexes('comments')}
    comment_fks = {fk['name'] for fk in inspector.get_foreign_keys('comments')}
    
    # 修改列注释（这些操作是幂等的，不会出错）
    op.alter_column('comments', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='评论内容',
               existing_nullable=False)
    op.alter_column('comments', 'content_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='内容类型',
               existing_nullable=False,
               existing_server_default=sa.text("'article'"))
    op.alter_column('comments', 'content_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='内容ID',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('comments', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               comment='评论者ID')
    op.alter_column('comments', 'parent_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='父评论ID',
               existing_nullable=True)
    op.alter_column('comments', 'reply_to_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='回复目标用户ID',
               existing_nullable=True)
    op.alter_column('comments', 'is_approved',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否审核通过',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('comments', 'like_count',
               existing_type=mysql.INTEGER(display_width=11),
               comment='点赞数',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('comments', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('comments', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    
    # 安全删除索引（如果存在）
    if 'ix_comments_content_type_id' in comment_indexes:
        op.drop_index(op.f('ix_comments_content_type_id'), table_name='comments')
    
    # 安全删除外键（如果存在）
    if 'comments_ibfk_2' in comment_fks:
        op.drop_constraint(op.f('comments_ibfk_2'), 'comments', type_='foreignkey')
    if 'comments_ibfk_3' in comment_fks:
        op.drop_constraint(op.f('comments_ibfk_3'), 'comments', type_='foreignkey')
    
    # 创建新外键（使用 try/except 处理已存在的情况）
    try:
        op.create_foreign_key('fk_comments_reply_to_id', 'comments', 'users', ['reply_to_id'], ['id'], ondelete='SET NULL')
    except Exception:
        pass
    try:
        op.create_foreign_key('fk_comments_parent_id', 'comments', 'comments', ['parent_id'], ['id'], ondelete='CASCADE')
    except Exception:
        pass
    try:
        op.create_foreign_key('fk_comments_user_id', 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    except Exception:
        pass
    
    # 安全删除列（如果存在）
    if 'email' in comment_columns:
        op.drop_column('comments', 'email')
    if 'nickname' in comment_columns:
        op.drop_column('comments', 'nickname')
    if 'avatar' in comment_columns:
        op.drop_column('comments', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('avatar', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True))
    op.add_column('comments', sa.Column('nickname', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.add_column('comments', sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_ibfk_3'), 'comments', 'comments', ['parent_id'], ['id'])
    op.create_foreign_key(op.f('comments_ibfk_2'), 'comments', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_comments_content_type_id'), 'comments', ['content_type', 'content_id'], unique=False)
    op.alter_column('comments', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('comments', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('comments', 'like_count',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='点赞数',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('comments', 'is_approved',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否审核通过',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('comments', 'reply_to_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='回复目标用户ID',
               existing_nullable=True)
    op.alter_column('comments', 'parent_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='父评论ID',
               existing_nullable=True)
    op.alter_column('comments', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               comment=None,
               existing_comment='评论者ID')
    op.alter_column('comments', 'content_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='内容ID',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('comments', 'content_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='内容类型',
               existing_nullable=False,
               existing_server_default=sa.text("'article'"))
    op.alter_column('comments', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='评论内容',
               existing_nullable=False)
    op.drop_column('categories', 'quote_author')
    op.drop_column('categories', 'quote')
    op.drop_column('categories', 'banner_url')
    # ### end Alembic commands ###
